# Generated by Django 5.0.3 on 2024-04-17 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testprep.test')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testprep.question')),
            ],
        ),
    ]
